-- MySQL Script generated by MySQL Workbench
-- Sun Apr 10 17:43:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema metaverso
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema metaverso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `metaverso` DEFAULT CHARACTER SET utf8 ;
USE `metaverso` ;

-- -----------------------------------------------------
-- Table `metaverso`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metaverso`.`enderecos` (
  `id_enderecos` INT NOT NULL,
  `tipo` VARCHAR(12) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(6) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `cep` VARCHAR(9) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `pais` VARCHAR(30) NOT NULL,
  `id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_enderecos`),
  UNIQUE INDEX `id_enderecos_UNIQUE` (`id_enderecos` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metaverso`.`telefones` (
  `id_telefones` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(9) NOT NULL,
  `id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_telefones`),
  UNIQUE INDEX `id_telefones_UNIQUE` (`id_telefones` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metaverso`.`emails` (
  `id_email` INT NOT NULL,
  `id_pessoa` INT NOT NULL,
  `endereco_eletronico` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_email`),
  UNIQUE INDEX `id_email_UNIQUE` (`id_email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metaverso`.`pessoa` (
  `id_pessoa` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `documento` VARCHAR(14) NOT NULL,
  `dt_nascimento` DATE NULL,
  `id_enderecos` INT NOT NULL,
  `id_telefone` INT NOT NULL,
  `id_email` INT NOT NULL,
  PRIMARY KEY (`id_pessoa`),
  UNIQUE INDEX `id_pessoa_UNIQUE` (`id_pessoa` ASC) VISIBLE,
  INDEX `id_endereco_idx` (`id_enderecos` ASC) VISIBLE,
  INDEX `id_telefone_idx` (`id_telefone` ASC) VISIBLE,
  INDEX `id_email_idx` (`id_email` ASC) VISIBLE,
  CONSTRAINT `id_enderecos`
    FOREIGN KEY (`id_enderecos`)
    REFERENCES `metaverso`.`enderecos` (`id_enderecos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_telefone`
    FOREIGN KEY (`id_telefone`)
    REFERENCES `metaverso`.`telefones` (`id_telefones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_email`
    FOREIGN KEY (`id_email`)
    REFERENCES `metaverso`.`emails` (`id_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metaverso`.`empresa` (
  `id_empresa` INT NOT NULL,
  `cnpj` INT(14) NULL,
  `razao_social` VARCHAR(100) NULL,
  `empresacol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_empresa`),
  UNIQUE INDEX `id_empresa_UNIQUE` (`id_empresa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metaverso`.`clientes` (
  `id_clientes` INT NOT NULL,
  `id_pessoa` INT NULL,
  `nivel_experiencia` INT NULL,
  `id_empresa` INT NULL,
  PRIMARY KEY (`id_clientes`),
  UNIQUE INDEX `id_clientes_UNIQUE` (`id_clientes` ASC) VISIBLE,
  INDEX `id_pessoa_idx` (`id_pessoa` ASC) VISIBLE,
  INDEX `id_empresa_idx` (`id_empresa` ASC) VISIBLE,
  CONSTRAINT `id_pessoa`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `metaverso`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `metaverso`.`empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`dispositivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metaverso`.`dispositivos` (
  `id_dispositivo` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `descricao` VARCHAR(500) NULL,
  PRIMARY KEY (`id_dispositivo`),
  INDEX `id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `metaverso`.`clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`tecnicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metaverso`.`tecnicos` (
  `id_tecnico` INT NOT NULL,
  `pontuacao_atendimento` FLOAT NOT NULL DEFAULT 0,
  `pontuacao_contribuicoes` INT NOT NULL DEFAULT 0,
  `id_empresa` INT NULL,
  `id_pessoa` INT NULL,
  PRIMARY KEY (`id_tecnico`),
  UNIQUE INDEX `id_tecnico_UNIQUE` (`id_tecnico` ASC) VISIBLE,
  INDEX `id_pessoa_idx` (`id_pessoa` ASC) VISIBLE,
  INDEX `id_empresa_idx` (`id_empresa` ASC) VISIBLE,
  CONSTRAINT `id_pessoa`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `metaverso`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `metaverso`.`empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`qualificacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metaverso`.`qualificacoes` (
  `id_qualificacoes` INT NOT NULL,
  `id_tecnico` INT NOT NULL,
  `tipo_qualificacao` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_qualificacoes`),
  INDEX `id_tecnico_idx` (`id_tecnico` ASC) VISIBLE,
  CONSTRAINT `id_tecnico`
    FOREIGN KEY (`id_tecnico`)
    REFERENCES `metaverso`.`tecnicos` (`id_tecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`portifolio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metaverso`.`portifolio` (
  `id_portifolio` INT NOT NULL,
  `id_tecnico` INT NOT NULL,
  `url` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_portifolio`),
  INDEX `id_tecnico_idx` (`id_tecnico` ASC) VISIBLE,
  CONSTRAINT `id_tecnico`
    FOREIGN KEY (`id_tecnico`)
    REFERENCES `metaverso`.`tecnicos` (`id_tecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`atendimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metaverso`.`atendimentos` (
  `id_atendimentos` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_tecnico` INT NOT NULL,
  `passou_faq` TINYINT NOT NULL,
  `passou_level` TINYINT NOT NULL,
  `tipo` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_atendimentos`),
  INDEX `id_tecnico_idx` (`id_tecnico` ASC) VISIBLE,
  INDEX `id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `id_tecnico`
    FOREIGN KEY (`id_tecnico`)
    REFERENCES `metaverso`.`tecnicos` (`id_tecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `metaverso`.`clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`avaliacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metaverso`.`avaliacoes` (
  `id_avaliacao` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `avaliacao` VARCHAR(1000) NOT NULL,
  `pontuacao_avaliacao` INT NOT NULL,
  `id_tecnico` INT NOT NULL,
  `id_atendimento` INT NOT NULL,
  PRIMARY KEY (`id_avaliacao`),
  INDEX `id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `id_tecnico_idx` (`id_tecnico` ASC) VISIBLE,
  INDEX `id_atendimento_idx` (`id_atendimento` ASC) VISIBLE,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `metaverso`.`clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_tecnico`
    FOREIGN KEY (`id_tecnico`)
    REFERENCES `metaverso`.`tecnicos` (`id_tecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_atendimento`
    FOREIGN KEY (`id_atendimento`)
    REFERENCES `metaverso`.`atendimentos` (`id_atendimentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
ROW_FORMAT = DEFAULT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
