-- MySQL Script generated by MySQL Workbench
-- Sun Apr 10 21:35:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema metaverso
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `metaverso` ;

-- -----------------------------------------------------
-- Schema metaverso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `metaverso` DEFAULT CHARACTER SET utf8 ;
USE `metaverso` ;

-- -----------------------------------------------------
-- Table `metaverso`.`enderecos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metaverso`.`enderecos` ;

CREATE TABLE IF NOT EXISTS `metaverso`.`enderecos` (
  `id_enderecos` INT NOT NULL,
  `tipo` VARCHAR(12) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(6) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `cep` VARCHAR(9) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `pais` VARCHAR(30) NOT NULL,
  `id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_enderecos`),
  UNIQUE INDEX `id_enderecos_UNIQUE` (`id_enderecos` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`telefones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metaverso`.`telefones` ;

CREATE TABLE IF NOT EXISTS `metaverso`.`telefones` (
  `id_telefones` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(9) NOT NULL,
  `id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_telefones`),
  UNIQUE INDEX `id_telefones_UNIQUE` (`id_telefones` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`emails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metaverso`.`emails` ;

CREATE TABLE IF NOT EXISTS `metaverso`.`emails` (
  `id_email` INT NOT NULL,
  `id_pessoa` INT NOT NULL,
  `endereco_eletronico` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_email`),
  UNIQUE INDEX `id_email_UNIQUE` (`id_email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metaverso`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `metaverso`.`pessoa` (
  `id_pessoa` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `documento` VARCHAR(14) NOT NULL,
  `dt_nascimento` DATE NULL,
  `id_enderecos` INT NOT NULL,
  `id_telefone` INT NOT NULL,
  `id_email` INT NOT NULL,
  PRIMARY KEY (`id_pessoa`),
  UNIQUE INDEX `id_pessoa_UNIQUE` (`id_pessoa` ASC),
  INDEX `id_endereco_idx` (`id_enderecos` ASC),
  INDEX `id_telefone_idx` (`id_telefone` ASC),
  INDEX `id_email_idx` (`id_email` ASC),
  CONSTRAINT `id_enderecos`
    FOREIGN KEY (`id_enderecos`)
    REFERENCES `metaverso`.`enderecos` (`id_enderecos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_telefone`
    FOREIGN KEY (`id_telefone`)
    REFERENCES `metaverso`.`telefones` (`id_telefones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_email`
    FOREIGN KEY (`id_email`)
    REFERENCES `metaverso`.`emails` (`id_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metaverso`.`empresa` ;

CREATE TABLE IF NOT EXISTS `metaverso`.`empresa` (
  `id_empresa` INT NOT NULL,
  `cnpj` INT(14) NULL,
  `razao_social` VARCHAR(100) NULL,
  `empresacol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_empresa`),
  UNIQUE INDEX `id_empresa_UNIQUE` (`id_empresa` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metaverso`.`clientes` ;

CREATE TABLE IF NOT EXISTS `metaverso`.`clientes` (
  `id_clientes` INT NOT NULL,
  `id_pessoa` INT NULL,
  `nivel_experiencia` INT NULL,
  `id_empresa` INT NULL,
  PRIMARY KEY (`id_clientes`),
  UNIQUE INDEX `id_clientes_UNIQUE` (`id_clientes` ASC),
  INDEX `id_pessoa_idx` (`id_pessoa` ASC),
  INDEX `id_empresa_idx` (`id_empresa` ASC),
  CONSTRAINT `id_pessoa`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `metaverso`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `metaverso`.`empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`dispositivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metaverso`.`dispositivos` ;

CREATE TABLE IF NOT EXISTS `metaverso`.`dispositivos` (
  `id_dispositivo` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `descricao` VARCHAR(500) NULL,
  PRIMARY KEY (`id_dispositivo`),
  INDEX `id_cliente_idx` (`id_cliente` ASC),
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `metaverso`.`clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`tecnicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metaverso`.`tecnicos` ;

CREATE TABLE IF NOT EXISTS `metaverso`.`tecnicos` (
  `id_tecnico` INT NOT NULL,
  `pontuacao_atendimento` FLOAT NOT NULL DEFAULT 0,
  `pontuacao_contribuicoes` INT NOT NULL DEFAULT 0,
  `id_empresa` INT NULL,
  `id_pessoa` INT NULL,
  PRIMARY KEY (`id_tecnico`),
  UNIQUE INDEX `id_tecnico_UNIQUE` (`id_tecnico` ASC),
  INDEX `id_pessoa_idx` (`id_pessoa` ASC),
  INDEX `id_empresa_idx` (`id_empresa` ASC),
  CONSTRAINT `id_pessoa`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `metaverso`.`pessoa` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `metaverso`.`empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`qualificacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metaverso`.`qualificacoes` ;

CREATE TABLE IF NOT EXISTS `metaverso`.`qualificacoes` (
  `id_qualificacoes` INT NOT NULL,
  `id_tecnico` INT NOT NULL,
  `tipo_qualificacao` VARCHAR(50) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_qualificacoes`),
  INDEX `id_tecnico_idx` (`id_tecnico` ASC),
  CONSTRAINT `id_tecnico`
    FOREIGN KEY (`id_tecnico`)
    REFERENCES `metaverso`.`tecnicos` (`id_tecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`portifolio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metaverso`.`portifolio` ;

CREATE TABLE IF NOT EXISTS `metaverso`.`portifolio` (
  `id_portifolio` INT NOT NULL,
  `id_tecnico` INT NOT NULL,
  `url` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_portifolio`),
  INDEX `id_tecnico_idx` (`id_tecnico` ASC),
  CONSTRAINT `id_tecnico`
    FOREIGN KEY (`id_tecnico`)
    REFERENCES `metaverso`.`tecnicos` (`id_tecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`atendimentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metaverso`.`atendimentos` ;

CREATE TABLE IF NOT EXISTS `metaverso`.`atendimentos` (
  `id_atendimentos` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_tecnico` INT NOT NULL,
  `passou_faq` TINYINT NOT NULL,
  `passou_level` TINYINT NOT NULL,
  `tipo` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_atendimentos`),
  INDEX `id_tecnico_idx` (`id_tecnico` ASC),
  INDEX `id_cliente_idx` (`id_cliente` ASC),
  CONSTRAINT `id_tecnico`
    FOREIGN KEY (`id_tecnico`)
    REFERENCES `metaverso`.`tecnicos` (`id_tecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `metaverso`.`clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`avaliacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metaverso`.`avaliacoes` ;

CREATE TABLE IF NOT EXISTS `metaverso`.`avaliacoes` (
  `id_avaliacao` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `avaliacao` VARCHAR(1000) NOT NULL,
  `pontuacao_avaliacao` INT NOT NULL,
  `id_tecnico` INT NOT NULL,
  `id_atendimento` INT NOT NULL,
  PRIMARY KEY (`id_avaliacao`),
  INDEX `id_cliente_idx` (`id_cliente` ASC),
  INDEX `id_tecnico_idx` (`id_tecnico` ASC),
  INDEX `id_atendimento_idx` (`id_atendimento` ASC),
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `metaverso`.`clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_tecnico`
    FOREIGN KEY (`id_tecnico`)
    REFERENCES `metaverso`.`tecnicos` (`id_tecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_atendimento`
    FOREIGN KEY (`id_atendimento`)
    REFERENCES `metaverso`.`atendimentos` (`id_atendimentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `metaverso`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metaverso`.`pedido` ;

CREATE TABLE IF NOT EXISTS `metaverso`.`pedido` (
  `id_pedido` INT NOT NULL,
  `id_clientes` INT NOT NULL,
  `data_pedido` DATETIME NOT NULL,
  `total` DOUBLE NOT NULL,
  `clientes_id_clientes` INT NOT NULL,
  PRIMARY KEY (`id_pedido`, `id_clientes`),
  INDEX `fk_pedido_clientes1_idx` (`clientes_id_clientes` ASC),
  CONSTRAINT `fk_pedido_clientes1`
    FOREIGN KEY (`clientes_id_clientes`)
    REFERENCES `metaverso`.`clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`pedido_copy1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metaverso`.`pedido_copy1` ;

CREATE TABLE IF NOT EXISTS `metaverso`.`pedido_copy1` (
  `id_pedido` INT NOT NULL,
  `id_clientes` INT NOT NULL,
  `data_pedido` DATETIME NOT NULL,
  `total` DOUBLE NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `id_cliente_idx` (`id_clientes` ASC),
  CONSTRAINT `id_cliente00`
    FOREIGN KEY (`id_clientes`)
    REFERENCES `metaverso`.`clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metaverso`.`produto` ;

CREATE TABLE IF NOT EXISTS `metaverso`.`produto` (
  `id_produto` INT NOT NULL,
  `titulo_produto` VARCHAR(150) NOT NULL,
  `descricao_produto` TEXT(250) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `nome_imagem` INT NOT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`item_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metaverso`.`item_pedido` ;

CREATE TABLE IF NOT EXISTS `metaverso`.`item_pedido` (
  `id_pedido` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `preco_unitario` DOUBLE NOT NULL,
  `quantidade` INT NOT NULL,
  `preco_total` DOUBLE NOT NULL,
  `produto_titulo_produto` VARCHAR(150) NOT NULL,
  `produto_id_produto` INT NOT NULL,
  PRIMARY KEY (`id_produto`, `id_pedido`),
  INDEX `fk_item_pedido_produto1_idx` (`produto_titulo_produto` ASC, `produto_id_produto` ASC),
  CONSTRAINT `fk_item_pedido_produto1`
    FOREIGN KEY (`produto_titulo_produto` , `produto_id_produto`)
    REFERENCES `metaverso`.`produto` (`titulo_produto` , `id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `metaverso`.`pedido_has_item_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metaverso`.`pedido_has_item_pedido` ;

CREATE TABLE IF NOT EXISTS `metaverso`.`pedido_has_item_pedido` (
  `pedido_id_pedido` INT NOT NULL,
  `pedido_id_clientes` INT NOT NULL,
  `item_pedido_id_produto` INT NOT NULL,
  `item_pedido_id_pedido` INT NOT NULL,
  PRIMARY KEY (`pedido_id_pedido`, `pedido_id_clientes`, `item_pedido_id_produto`, `item_pedido_id_pedido`),
  INDEX `fk_pedido_has_item_pedido_item_pedido1_idx` (`item_pedido_id_produto` ASC, `item_pedido_id_pedido` ASC),
  INDEX `fk_pedido_has_item_pedido_pedido1_idx` (`pedido_id_pedido` ASC, `pedido_id_clientes` ASC),
  CONSTRAINT `fk_pedido_has_item_pedido_pedido1`
    FOREIGN KEY (`pedido_id_pedido` , `pedido_id_clientes`)
    REFERENCES `metaverso`.`pedido` (`id_pedido` , `id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_item_pedido_item_pedido1`
    FOREIGN KEY (`item_pedido_id_produto` , `item_pedido_id_pedido`)
    REFERENCES `metaverso`.`item_pedido` (`id_produto` , `id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
